# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4ffbb2625aca4ca3bd80dabfaaaa47c3e6c74c44a29b1e038414185e7cbfdeb03d2e6b2c7b23585015f7759ee7e73ce2f0d2cb09341d55b1f430e1acecc990d

test:
  secret_key_base: e3ca2138ee6f39f7e46e002a9d66f985fc468b8c332df86c96964f29ff8d9e41d30018f2607ca987c8d09864585cc1be85a6aaa60f8f91f0f0c23941d31bc29c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
